### ISSUE TITLE
Breakdown by topic

### ISSUE THREAD

**Issue by Kacuga** [sklyar/docker-log-driver-telegram#2]
Hi! I really like your decision to send logs to telegram
Can you tell me if it is planned to split the sending of logs within the same channel on different topics?(message_thread_id)

**Comment by sklyar** [comment]
Hi! I'm glad you find the project useful.

I hadn't planned to implement splitting logs within the same channel on different topics (message_thread_id), but I can add it, it shouldn't be too difficult. If you know Go, feel free to submit a pull request.

**Comment by Kacuga** [comment]
Hello, Friend!
Couldn't learn such a function?

**Comment by sklyar** [comment]
Hi! 

I don’t plan to support splitting logs within the same channel using different topics. I feel it would make the driver unnecessarily complex. Right now, you can simply create a new Telegram channel, and I don’t see that as a big deal.
