### ISSUE TITLE
Send multiple lines as batch to speed up sending rapid successive log messages

### ISSUE THREAD

**Issue by floriegl** [sklyar/docker-log-driver-telegram#3]
When my Docker container starts, it generates around 100 log messages within the first second. It takes about 5 minutes for all these logs to be sent via the Telegram bot, which also delays their appearance in `docker logs`.

Is it possible to optionally optimize the Telegram API calls by batching multiple log messages into a single request? For instance, the bot could include all log lines generated since the last API call, up to the maximum allowed by the Telegram API, which would significantly reduce the number of calls and improve the speed of logging messages.

If batching isn't feasible, could the `docker logs` output avoid being delayed while the logs are being sent via Telegram?

**Comment by sklyar** [comment]
Thank you for bringing up this issue. I’ve looked into the Telegram API, and unfortunately, it does not support batching for messages. However, we can explore the idea of implementing batching on the logging driver side. This way, we could combine multiple log messages into a single message.

Keep in mind that there is a limitation of 4096 characters for the message size. If the logs are relatively small, this could be a viable solution. However, if the logs are larger, it might not be as effective.

**Comment by floriegl** [comment]
Yeah, this was pretty much my idea:
If the client is currently rate limited e.g., has to wait on `c.limiter.Take()` or got `http.StatusTooManyRequests` on `SendMessage`, save the current log line in e.g., a list and do the normal retry mechanism with as many stored log lines joined with \n as possible, while still staying under the `maxLogSize`.

**Comment by sklyar** [comment]
I think a simpler approach would be to implement log batching and send messages either when the batch size limit is reached or after a set timeout. This way, we can reduce the number of API calls and manage bursts of logs more efficiently.

One important limitation to keep in mind is how Docker plugins work. Docker log drivers don’t run continuously in the background. They’re only activated when a new log message is generated. This means that if logs stop coming in, any logs that are still in the buffer won’t be sent immediately—they’ll just sit there until the next log triggers a flush. This could lead to delays in sending the last logs if the container becomes idle.

The timeout mechanism would help reduce this risk, but there’s still a chance that buffered logs won’t be sent promptly if no new logs come in. Let me know if you think this approach makes sense.

**Comment by sklyar** [comment]
> If batching isn't feasible, could the docker logs output avoid being delayed while the logs are being sent via Telegram?

I'll look into whether it's possible to avoid the delays and get back to you.
